/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1b1c1c',
        'inverse-primary': '#ffb59a',
        'background': '#eeedef',
        'surface': '#faf9f9',
        'surface-bright': '#faf9f9',
        'surface-variant': '#e3e2e2',
        'inverse-on-surface': '#f2f0f0',
        'on-tertiary-container': '#383838',
        'on-error': '#ffffff',
        'tertiary': '#5f5e5e',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#ffdbcf',
        'surface-tint': '#a73a05',
        'on-tertiary-fixed': '#1b1c1c',
        'on-secondary-fixed': '#1a1c1c',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary-fixed-variant': '#454747',
        'on-background': '#1b1c1c',
        'surface-container-low': '#f4f3f3',
        'primary-container': '#ff7a45',
        'surface-container-high': '#e9e8e8',
        'primary': '#a73a05',
        'tertiary-fixed': '#e4e2e1',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#ffb59a',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#802900',
        'inverse-surface': '#2f3031',
        'surface-dim': '#dbdad9',
        'on-primary': '#ffffff',
        'outline-variant': '#dfc0b5',
        'on-surface-variant': '#58423a',
        'outline': '#8b7168',
        'on-tertiary-fixed-variant': '#474747',
        'on-secondary-container': '#5f6161',
        'on-primary-fixed': '#380d00',
        'secondary': '#5d5f5f',
        'tertiary-fixed-dim': '#c8c6c6',
        'surface-container': '#efeded',
        'on-error-container': '#93000a',
        'secondary-container': '#dcdddd',
        'surface-container-highest': '#e3e2e2',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#a2a1a1',
        'secondary-fixed': '#e2e2e2',
        'on-primary-container': '#672000',
        'error': '#ba1a1a',
        'success': '#1b8a3a',
        'warning': '#b8860b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '16px',
        'sm': '8px',
        'md': '16px',
        'base': '8px',
        'xl': '32px',
        'lg': '24px',
        'xs': '4px',
        'container-padding': '16px',
      },
      fontFamily: {
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Work Sans', 'sans-serif'],
        'label-bold': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'caption': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  safelist: [
    'text-success',
    'bg-success/10',
    'text-yellow-500',
    'bg-yellow-500/10',
    'bg-surface-container-high',
    'bg-primary-fixed',
    'bg-error-container',
    'text-on-error-container',
  ],
  plugins: [],
}
